Testing
YunoHost-Apps/webtrees_ynh pull request #14
Opened 2020-11-09 15:20 UTC by ericgaspar

## Problem
- *New version upstream*

## Solution
- *Upgrade to v 2.0.10*
- *Remove rm -rf #13*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/webtrees_ynh%20PR-NUM-%20(ericgaspar)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/webtrees_ynh%20PR-NUM-%20(ericgaspar)/)

2020-11-10 18:56 UTC, yalh76 requested changes

2020-11-10 18:56 UTC, yalh76 commented on scripts/upgrade
> +ynh_secure_remove ${final_path}.old
```suggestion
ynh_secure_remove --file=${final_path}.old
```

2020-11-10 22:08 UTC, yalh76 approved these changes

2020-11-11 00:09 UTC, anmol26s commented on scripts/remove
> +ynh_script_progression --message="Removal of Webtrees completed"
Will this not provide the app instance name here? What if the user have multiple instances?And he will not be given with correct instance name.

2020-11-11 08:49 UTC, ericgaspar commented on scripts/remove
> +ynh_script_progression --message="Removal of Webtrees completed"
Point taken -> d428b3a

2020-11-11 09:04 UTC, ericgaspar commented
Maybe the registration password process should be changed for this app:
For the moment, the password is generated randomly by the app and sent to the administrator by e-mail.

**Two problems:**
- A user [issued](https://forum.yunohost.org/t/packagers-this-app-is-still-using-the-skipped-protected-unprotected-uris-regex-settings/13252/7) that the e-mail with the password does not reach his mailbox and therefore cannot log in.
What about letting the user choose their password during the installation process?
- Users will also complain that the password is sent in clear by e-mail.
If the password is chosen by the administrator, do we need to send an e-mail?

2020-11-12 14:31 UTC, merged